version: "3.1"

services:
    sim-database:
        image: postgres:latest
        container_name: sim-database
        restart: always
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: simulator-database
        tty: true
        networks:
            - local_net

    simulator:
        restart: always
        build:
            context: .
            dockerfile: ./docker-files/Dockerfile
        container_name: simulator
        image: simulator
        ports:
            - "5000:5000"
        volumes:
            - ./:/app
        environment:
            RDS_ENGINE:   postgresql
            RDS_HOSTNAME: sim-database
            RDS_USERNAME: postgres
            RDS_PASSWORD: mysecretpassword
            RDS_PORT:     5432
            RDS_DB_NAME:  simulator-database
        tty:
            true
        networks:
            - local_net

    client-1:
        restart: always
        build:
            context: .
            dockerfile: ./docker-files/Dockerfile.client
        container_name: client-1
        image: client-1
        command: sh -c "sleep 5; python3 src/client/car.py"
        volumes:
            - ./:/app
        tty: true
        networks:
            - local_net

networks:
    local_net:
        external: false
