version: "3.1"

services:
    # server-db:
    #     restart: always
    #     image: keinos/sqlite3:latest
    #     container_name: server-db
    #     tty: true
    #     networks:
    #         - local_net

    simulator:
        restart: always
        build:
            context: .
            dockerfile: ./docker-files/Dockerfile
        container_name: simulator
        image: simulator
        ports:
            - "5000:5000"
        volumes:
            - ./:/app
        tty:
            true
        networks:
            - local_net

    client-1:
        restart: always
        build:
            context: .
            dockerfile: ./docker-files/Dockerfile.client
        container_name: client-1
        image: client-1
        command: sh -c "sleep 5; python3 src/client/car.py"
        volumes:
            - ./:/app
        tty: true
        networks:
            - local_net

networks:
    local_net:
        external: false
