FROM python:latest

RUN pip3 install requests

# Create system user group and add new user.
# RUN groupadd -r sim_user && useradd -r -s /bin/false -g sim_user sim_user

# Make new user owner of project directory.
RUN mkdir /app
WORKDIR   /app
# COPY .    /app

# RUN chown -R sim_user:sim_user /app

# Switch to non-root user after setup and installations.
# USER sim_user

